# Default or base configuration for SE(3) diffusion experiments.

defaults:
  - override hydra/launcher: joblib

data:
  csv_path: /data/rsg/chemistry/jyim/large_data/processed_pdb_protdiff/metadata.csv
  filtering:
    max_len: 512
    min_len: 60
    # Set to null for no subset selection.
    subset: null
    allowed_oligomer: [monomeric]
    max_helix_percent: 1.0
    max_loop_percent: 0.5
    min_beta_percent: -1.0
    rog_quantile: 0.0
  hallucination_percent: 1.0
  aatype_masking: False
  mixed_t: False
  motif_size_min: 10
  scaffold_size_min: 10
  scaffold_size_max: 200
  min_t: 0.01
  has_splits: False
  samples_per_cath: 1
  samples_per_eval_length: 4
  num_eval_lengths: 10
  num_t: 100

diffuser:
  se3:
    diffuse_trans: True
    diffuse_rot: True

    # R(3) diffuser arguments
    r3:
      min_b: 0.1
      max_b: 20.0
      schedule: linear
      score_scaling: std 
      coordinate_scaling: 0.1

    # SO(3) diffuser arguments
    so3:
      num_omega: 1000
      num_sigma: 1000
      min_sigma: 0.1
      max_sigma: 1.5
      schedule: logarithmic
      equivariant_score: False
      cache_dir: ./pkl_jar/
      score_scaling: std

model:
  node_embed_size: 256
  edge_embed_size: 128
  dropout: 0.0
  network_type: ipa
  equivariant_rot_score: ${diffuser.se3.so3.equivariant_score}
  rigid_prediction: True
  aatype_prediction: ${diffuser.seq.diffuse_seq}
  embed:
    index_embed_size: 32
    aatype_embed_size: 64
    embed_aatype: False
    embed_chain_idx: False
    embed_self_conditioning: True
    mixed_t: ${data.rosetta.mixed_t}
    num_bins: 22
    min_bin: 1e-5
    max_bin: 20.0
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    ipa_skip_residual: True
    c_hidden: 256
    c_skip: 64
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 4
    aatype_head_layers: 2
    coordinate_scaling: ${diffuser.se3.r3.coordinate_scaling}
    tfmr_skip_residual: True
    pred_rot_score: False
    embed_distogram: False
  se3_tfmr:
    num_channels: 32
    num_degrees: 2
    n_heads: 4
    div: 4
    l0_in_features: ${model.node_embed_size}
    l0_out_features: ${model.node_embed_size}
    l1_in_features: 2
    l1_out_features: 2
    num_edge_features: ${model.edge_embed_size} 
    num_layers: 2

experiment:
  name: baseline
  data_location: rosetta
  wandb_dir: ./
  run_id: null
  log_freq: 1000
  batch_size: 256
  eval_batch_size: ${data.rosetta.samples_per_eval_length}
  num_loader_workers: 10
  num_epoch: 1000000
  learning_rate: 0.0001
  use_scheduler: False
  ckpt_dir: ./pkl_jar/ckpt/
  max_squared_res: 1000000
  use_gpu: True
  sample_mode: time_batch
  # How many steps to checkpoint between.
  ckpt_freq: 10000
  early_ckpt: True
  # Checkpoint directory to warm start from.
  warm_start: null
  use_warm_start_conf: False
  port: 12319
  dist_mode: multi
  multi_gpu_size: 2
  use_wandb: True
  prefetch_factor: 100
  # Loss weights.
  trans_loss_weight: 1.0
  rot_loss_weight: 1.0
  psi_loss_weight: 0.0
  psi_loss_t_filter: 0.4
  trans_x0_threshold: 1.0
  coord_loss_scaling: ${diffuser.se3.r3.coordinate_scaling}
  bb_atom_loss_weight: 1.0
  bb_atom_loss_t_filter: 0.25
  bb_atom_scaling: 0.5
  aatype_loss_weight: 1.0
  dist_mat_loss_weight: 1.0
  dist_mat_loss_t_filter: 0.25
  dist_mat_scaling: 0.5
  likelihood_metric: False
  # Evaluation.
  eval_dir: ./results
  noise_scale: 1.0
  # Filled in during training.
  num_parameters: null
