# Default or base configuration for SE(3) diffusion experiments.

defaults:
  - override hydra/launcher: joblib

data:
  digs:
    server_dir: /projects/ml/TrRosetta
    base_pdb_dir: ${data.digs.server_dir}/PDB-2021AUG02
    base_fb_dir: ${data.digs.server_dir}/fb_af
    pdb_csv: ${data.digs.base_pdb_dir}/list_v02.csv
    pdb_dir: ${data.digs.base_pdb_dir}/torch/pdb
    fb_dir: ${data.digs.base_fb_dir}/pdb
    fb_msa_dir: ${data.digs.base_fb_dir}/a3m
    valid_clusters: ${data.digs.base_pdb_dir}/val/xaa
    fb_csv: ${data.digs.base_fb_dir}/list_b1-3.csv
    filtering:
      resolution_cutoff: 5.0
      max_len: 260
      min_len: 60
      min_plddt: 80.0
      min_fb_len: 100
      date_cutoff: 2020-Apr-30
      subset: null
    cache_dir: ./pkl_jar/
    epoch_size: 1000
    fraction_fb: 0.0
    crop_len: null
    scale_factor: 10.0
    t_sampler: 'scheduled'
    num_t: 500
  rosetta:
    csv_path: /data/rsg/chemistry/jyim/large_data/processed_pdb_protdiff/metadata.csv
    filtering:
      max_len: 260
      min_len: 60
      # Set to null for no subset selection.
      subset: null
      # TODO: Enable working beyond monomers.
      allowed_oligomer: [monomeric]
      max_helix_percent: 0.7
      max_loop_percent: 0.5
      min_beta_percent: 0.1
      rog_quantile: 0.96
    samples_per_eval_length: 4
    num_eval_lengths: 10
    scale_factor: 10.0
    t_sampler: 'scheduled'
    num_t: 500

diffuser:
  # R(3) diffuser arguments
  trans_min_b: 0.1
  trans_max_b: 7.5
  trans_num_t: 1000
  trans_schedule: linear
  trans_align_t: False
  # SO(3) diffuser arguments
  num_omega: 1000
  num_sigma: 1000
  rot_min_sigma: 0.1
  rot_max_sigma: 1.5
  rot_schedule: logarithmic
  diffuse_trans: True
  diffuse_rot: True
  equivariant_rot_score: False
  igso3_cache_dir: ./pkl_jar/

model:
  node_embed_size: 256
  edge_embed_size: 128
  num_blocks: 3
  dropout: 0.0
  network_type: ipa
  l0_scale: 100
  l1_scale: 100
  scale_factor: 1.0
  index:
    index_embed_size: 64
    node_embed_size: ${model.node_embed_size}
    edge_embed_size: ${model.edge_embed_size}
    use_res_idx_encoding: True 
    use_rel_idx_encoding: True
    embed_aatype: True
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 256
    no_heads: 8
    no_qk_points: 12
    no_v_points: 8
    local_projection: True
  se3_tfmr:
    num_channels: 32
    num_degrees: 2
    n_heads: 4
    div: 4
    l0_in_features: ${model.node_embed_size}
    l0_out_features: ${model.node_embed_size}
    l1_in_features: 2
    l1_out_features: 2
    num_edge_features: ${model.edge_embed_size} 
    num_layers: 2

experiment:
  name: baseline
  data_location: rosetta
  wandb_dir: ./
  run_id: null
  log_freq: 1000
  batch_size: 16
  num_loader_workers: 4
  num_epoch: 10000
  learning_rate: 0.0001
  ckpt_dir: ./pkl_jar/ckpt/
  # How many steps to checkpoint between.
  ckpt_freq: 10000
  # Checkpoint directory to warm start from.
  warm_start: null
  use_warm_start_conf: True
  port: 12319
  dist_mode: single
  use_wandb: True
  prefetch_factor: 100
  # Loss weights
  trans_loss_weight: 1.0
  rot_loss_weight: 1.0
  psi_loss_weight: 1.0
  psi_loss_t_filter: 0.2
  # Evaluation
  eval_dir: ./results

