defaults:
  - base

data:
  rosetta:
    scale_factor: 1.0
    num_t: 1000

diffuser:
  trans_max_b: 20

model:
  scale_factor: 10.0

experiment:
  name: black_hole

hydra:
  sweeper:
    params:
      data.rosetta.filtering.subset: 1000,null

