defaults:
  - base

data:
  rosetta:
    filtering:
      subset: 1
      max_len: 80
    num_eval_lengths: 1
    scale_factor: 1.0
    num_t: 1000

diffuser:
  trans_max_b: 20

model:
  scale_factor: 10.0

experiment:
  name: single_example_black_hole

hydra:
  sweeper:
    params:
