defaults:
  - base

data:
  digs:
    filtering:
      subset: 1000

diffuser:
  trans_schedule: linear
  rot_schedule: logarithmic
  rot_max_sigma: 2.5
  trans_max_b: 14.0

experiment:
  name: subset_1000_lin_log_4
  dist_mode: single
  data_location: digs
