defaults:
  - base

data:
  digs:
    filtering:
      subset: 1000

diffuser:
  diffuse_rots: False
  diffuse_trans: True

experiment:
  name: subset_1000_only_trans
  dist_mode: single
  data_location: digs
