defaults:
  - base

data:
  digs:
    filtering:
      subset: 1000

diffuser:
  trans_schedule: linear
  rot_schedule: logarithmic
  rot_max_sigma: 1.5
  trans_max_b: 7.5

experiment:
  name: subset_1000_lin_log_3
  dist_mode: single
  data_location: digs
