defaults:
  - base_no_mr
  - openfold_lr_scheduler_base

experiment:
  name: toy_lr_scheduler

openfold_lr_scheduler:  
  last_epoch: -1
  verbose: False
  base_lr: 0
  max_lr: 0.0001
  warmup_no_steps: 10
  start_decay_after_n_steps: 100
  decay_every_n_steps: 10
  decay_factor: 0.95